-- ============================================================
-- IGD OCMS Database Schema
-- Run this against your PostgreSQL database to create all tables.
-- ============================================================

-- Enable UUID generation (built-in in PostgreSQL 13+)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -------------------------------------------------------
-- COMPLAINT
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS complaint (
    "Timestamp" text,
    "Name of The Accused" text,
    "Position of The Accused" text,
    "Company of The Accused" text,
    "Type of Complaint" text,
    "Details of Complaint" text,
    "Date of Incident" text,
    "Time of Incident (General)" text,
    "Location of Incident" text,
    "Other involved parties (If applicable)" text,
    "Upload file if there are evidences" text,
    "Email address" text,
    "Your Phone Number" bigint,
    "Your Name" text,
    "Status" text,
    "Tracking ID" text,
    "Complaint Reference ID" text,
    "Remarks" text,
    "Last Updated Date" text,
    "Notify Complainant" text,
    "Last Email Sent" text,
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    "FollowupToken" uuid,
    "AdminRemarks" text,
    "LastReviewDate" timestamp without time zone,
    "FollowupFiles" jsonb DEFAULT '[]'::jsonb,
    "FollowupResponse" text,
    "Source" text DEFAULT 'WEBSITE'::text,
    "Email UID" text,
    "AI Confidence" integer,
    "Needs Review" boolean DEFAULT false,
    CONSTRAINT complaint_pkey PRIMARY KEY (id)
);

-- -------------------------------------------------------
-- GOVERNANCE
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS governance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    file_url text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by text,
    updated_by text
);

-- -------------------------------------------------------
-- INTEGRITY EVENTS
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS integrity_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date text NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    images jsonb DEFAULT '[]'::jsonb
);

-- -------------------------------------------------------
-- RESOURCES
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS resources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    file_url text NOT NULL,
    file_size text NOT NULL,
    updated_date text NOT NULL,
    icon text NOT NULL DEFAULT 'document'::text,
    created_at timestamp with time zone DEFAULT now()
);

-- -------------------------------------------------------
-- CONTACT MESSAGES
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS contact_messages (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL,
    message text NOT NULL,
    created_at timestamp without time zone DEFAULT now()
);

-- -------------------------------------------------------
-- ADMIN USERS
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL UNIQUE,
    email text UNIQUE,
    password_hash text NOT NULL,
    role text DEFAULT 'admin'::text,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- -------------------------------------------------------
-- PROCESSED EMAILS
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS processed_emails (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id text NOT NULL UNIQUE,
    processed_at timestamp with time zone DEFAULT now()
);

-- -------------------------------------------------------
-- AUDIT LOGS
-- -------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    admin_id text NOT NULL,
    action_type text NOT NULL,
    target text,
    details jsonb,
    session_id uuid NOT NULL,
    timestamp timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
